PublicDateAtUSN: 2012-07-31
Candidate: CVE-2012-3444
PublicDate: 2012-07-31 17:55:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-3444
 https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued/
 http://www.openwall.com/lists/oss-security/2012/07/31/1
 http://www.openwall.com/lists/oss-security/2012/07/31/2
 https://ubuntu.com/security/notices/USN-1560-1
Description:
 The get_image_dimensions function in the image-handling functionality in
 Django before 1.3.2 and 1.4.x before 1.4.1 uses a constant chunk size in
 all attempts to determine dimensions, which allows remote attackers to
 cause a denial of service (process or thread consumption) via a large TIFF
 image.
Ubuntu-Description:
Notes:
 mdeslaur> possible regression, see LP: #1031733
Bugs:
 http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=683364
 https://bugs.launchpad.net/ubuntu/+source/python-django/+bug/1031733
Priority: medium
Discovered-by: Jeroen Dekkers
Assigned-to:
CVSS: 

Patches_python-django:
 vendor: http://www.debian.org/security/2012/dsa-2529
 upstream: https://github.com/django/django/commit/b2eb4787a0fff9c9993b78be5c698e85108f3446
upstream_python-django: released (1.3.2,1.4.1)
hardy_python-django: ignored (reached end-of-life)
lucid_python-django: released (1.1.1-2ubuntu1.5)
natty_python-django: released (1.2.5-1ubuntu1.2)
oneiric_python-django: released (1.3-2ubuntu1.3)
precise_python-django: released (1.3.1-4ubuntu1.2)
devel_python-django: not-affected (1.4.1-1)
