Candidate: CVE-2016-9015
PublicDate: 2017-01-11 16:59:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-9015
 https://marc.info/?l=oss-security&m=147756761531433&w=2
Description:
 Versions 1.17 and 1.18 of the Python urllib3 library suffer from a
 vulnerability that can cause them, in certain configurations, to not
 correctly validate TLS certificates. This places users of the library with
 those configurations at risk of man-in-the-middle and information leakage
 attacks. This vulnerability affects users using versions 1.17 and 1.18 of
 the urllib3 library, who are using the optional PyOpenSSL support for TLS
 instead of the regular standard library TLS backend, and who are using
 OpenSSL 1.1.0 via PyOpenSSL. This is an extremely uncommon configuration,
 so the security impact of this vulnerability is low.
Ubuntu-Description:
Notes:
 seth-arnold> I'm marking our packages 'not-affected' due to upstream version
  notes.
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N [3.7 LOW]

Patches_python-urllib3:
upstream_python-urllib3: released (1.18.1)
precise_python-urllib3: DNE
trusty_python-urllib3: not-affected
trusty/esm_python-urllib3: not-affected
vivid/stable-phone-overlay_python-urllib3: DNE
vivid/ubuntu-core_python-urllib3: not-affected
xenial_python-urllib3: not-affected
esm-infra/xenial_python-urllib3: not-affected
yakkety_python-urllib3: not-affected
devel_python-urllib3: not-affected
