Candidate: CVE-2021-3572
PublicDate: 2021-06-11 00:00:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3572
 https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1926957
 https://github.com/pypa/pip/pull/9827
 https://github.com/pypa/pip/commit/ca832b2836e0bffa7cf95589acdcd71230f5834e (21.1)
Description:
 [Don&#x27;t split git references on unicode separators #9827]
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: low
Discovered-by:
Assigned-to:
CVSS:


Patches_python-pip:
upstream_python-pip: released (20.3.4-2)
trusty_python-pip: ignored (out of standard support)
trusty/esm_python-pip: needs-triage
xenial_python-pip: ignored (out of standard support)
bionic_python-pip: needs-triage
focal_python-pip: needs-triage
groovy_python-pip: ignored (reached end-of-life)
hirsute_python-pip: needs-triage
devel_python-pip: needs-triage
