Candidate: CVE-2024-1141
PublicDate: 2024-02-01 15:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-1141
 https://access.redhat.com/security/cve/CVE-2024-1141
Description:
 A vulnerability was found in python-glance-store. The issue occurs when the
 package logs the access_key for the glance-store when the DEBUG log level
 is enabled.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 https://bugzilla.redhat.com/show_bug.cgi?id=2258836
 https://bugs.launchpad.net/glance-store/+bug/2047688
Priority: medium
Discovered-by:
Assigned-to: mdeslaur
CVSS:

Patches_python-glance-store:
 upstream: https://github.com/openstack/glance_store/commit/a5ba027922ba1230b4ae9abb810f36427be6354a
 upstream: https://github.com/openstack/glance_store/commit/d6e531af4821c8466b1e9404f12f89f6216417f2
upstream_python-glance-store: needs-triage
trusty_python-glance-store: DNE
xenial_python-glance-store: ignored (end of standard support)
esm-infra/xenial_python-glance-store: needs-triage
bionic_python-glance-store: ignored (end of standard support)
esm-infra/bionic_python-glance-store: needs-triage
focal_python-glance-store: needs-triage
jammy_python-glance-store: needs-triage
mantic_python-glance-store: needs-triage
devel_python-glance-store: needs-triage
