Candidate: CVE-2021-3426
PublicDate: 2021-03-12 00:00:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3426
 https://bugs.python.org/issue42988
 https://python-security.readthedocs.io/vuln/pydoc-getfile.html
 https://github.com/python/cpython/pull/24337
 https://github.com/python/cpython/pull/24285
Description:
 [Unknown description]
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:


Patches_python3.9:
upstream_python3.9: needs-triage
precise/esm_python3.9: DNE
trusty_python3.9: ignored (out of standard support)
trusty/esm_python3.9: DNE
xenial_python3.9: DNE
bionic_python3.9: DNE
focal_python3.9: needs-triage
groovy_python3.9: needs-triage
devel_python3.9: needs-triage

Patches_python3.7:
upstream_python3.7: needs-triage
precise/esm_python3.7: DNE
trusty_python3.7: ignored (out of standard support)
trusty/esm_python3.7: DNE
xenial_python3.7: DNE
bionic_python3.7: needs-triage
focal_python3.7: DNE
groovy_python3.7: DNE
devel_python3.7: DNE

Patches_python3.5:
upstream_python3.5: needs-triage
precise/esm_python3.5: DNE
trusty_python3.5: ignored (out of standard support)
trusty/esm_python3.5: needs-triage
xenial_python3.5: needs-triage
bionic_python3.5: DNE
focal_python3.5: DNE
groovy_python3.5: DNE
devel_python3.5: DNE

Patches_python2.7:
upstream_python2.7: not-affected (debian: Vulnerable code not present)
precise/esm_python2.7: needs-triage
trusty_python2.7: ignored (out of standard support)
trusty/esm_python2.7: needs-triage
xenial_python2.7: needs-triage
bionic_python2.7: needs-triage
focal_python2.7: needs-triage
groovy_python2.7: needs-triage
devel_python2.7: needs-triage
