Candidate: CVE-2021-3572
PublicDate: 2021-11-10 18:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3572
 https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1926957
 https://github.com/pypa/pip/pull/9827
 https://github.com/pypa/pip/commit/ca832b2836e0bffa7cf95589acdcd71230f5834e (21.1)
Description:
 A flaw was found in python-pip in the way it handled Unicode separators in
 git references. A remote attacker could possibly use this issue to install
 a different revision on a repository. The highest threat from this
 vulnerability is to data integrity. This is fixed in python-pip version
 21.1.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: low
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N


Patches_python-pip:
upstream_python-pip: released (20.3.4-2)
trusty_python-pip: ignored (out of standard support)
trusty/esm_python-pip: needs-triage
xenial_python-pip: ignored (out of standard support)
bionic_python-pip: needs-triage
focal_python-pip: needs-triage
groovy_python-pip: ignored (reached end-of-life)
hirsute_python-pip: ignored (reached end-of-life)
impish_python-pip: needs-triage
devel_python-pip: needs-triage
