Candidate: CVE-2023-28859
PublicDate: 2023-03-27
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28859
 https://github.com/redis/redis-py/pull/2641
 https://github.com/redis/redis-py/issues/2665
Description:
 redis-py through 4.5.3 leaves a connection open after canceling an async
 Redis command at an inopportune time (in the case of a non-pipeline
 operation), and can send response data to the client of an unrelated
 request. NOTE: this issue exists because of an incomplete fix for
 CVE-2023-28858.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:

Patches_python-redis:
upstream_python-redis: needs-triage
esm-infra/xenial_python-redis: needs-triage
trusty_python-redis: ignored (out of standard support)
xenial_python-redis: ignored (out of standard support)
bionic_python-redis: needs-triage
focal_python-redis: needs-triage
jammy_python-redis: needs-triage
kinetic_python-redis: needs-triage
devel_python-redis: needs-triage
