Candidate: CVE-2021-41495
PublicDate: 2021-12-17 20:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-41495
 https://github.com/numpy/numpy/issues/19038
 https://github.com/numpy/numpy/pull/20984 (backport)
 https://github.com/numpy/numpy/pull/20960
Description:
 ** DISPUTED ** Null Pointer Dereference vulnerability exists in numpy.sort
 in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing
 return-value validation, which allows attackers to conduct DoS attacks by
 repetitively creating sort arrays. NOTE: While correct that validation is
 missing, an error can only occur due to an exhaustion of memory. If the
 user can exhaust memory, they are already privileged. Further, it should be
 practically impossible to construct an attack which can target the memory
 exhaustion to occur at exactly this place.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: 0xnishit
CVSS:
 nvd: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H [5.3 MEDIUM]


Patches_numpy:
upstream_numpy: released (1.22.2, 1.23.0)
trusty_numpy: ignored (out of standard support)
xenial_numpy: ignored (out of standard support)
focal_numpy: needs-triage
hirsute_numpy: ignored (reached end-of-life)
impish_numpy: ignored (reached end-of-life)
jammy_numpy: needs-triage
kinetic_numpy: needs-triage
devel_numpy: needs-triage
