Candidate: CVE-2021-42343
PublicDate: 2021-10-26 11:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42343
Description:
 An issue was discovered in the Dask distributed package before 2021.10.0
 for Python. Single machine Dask clusters started with
 dask.distributed.LocalCluster or dask.distributed.Client (which defaults to
 using LocalCluster) would mistakenly configure their respective Dask
 workers to listen on external interfaces (typically with a randomly
 selected high port) rather than only on localhost. A Dask cluster created
 using this method (when running on a machine that has an applicable port
 exposed) could be used by a sophisticated attacker to achieve remote code
 execution.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H [9.8 CRITICAL]


Patches_dask:
upstream_dask: needs-triage
trusty_dask: ignored (out of standard support)
xenial_dask: ignored (out of standard support)
bionic_dask: needs-triage
focal_dask: needs-triage
hirsute_dask: ignored (reached end-of-life)
impish_dask: ignored (reached end-of-life)
jammy_dask: needs-triage
devel_dask: needs-triage
