Candidate: CVE-2023-28858
PublicDate: 2023-03-27
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28858
 https://github.com/redis/redis-py/compare/v4.3.5...v4.3.6
 https://github.com/redis/redis-py/pull/2641
 https://openai.com/blog/march-20-chatgpt-outage
 https://github.com/redis/redis-py/issues/2624
 https://github.com/redis/redis-py/compare/v4.4.2...v4.4.3
 https://github.com/redis/redis-py/compare/v4.5.2...v4.5.3
Description:
 redis-py before 4.5.3, as used in ChatGPT and other products, leaves a
 connection open after canceling an async Redis command at an inopportune
 time (in the case of a pipeline operation), and can send response data to
 the client of an unrelated request in an off-by-one manner. The fixed
 versions for this CVE Record are 4.3.6, 4.4.3, and 4.5.3; however,
 CVE-2023-28859 is a separate vulnerability.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:

Patches_python-redis:
upstream_python-redis: needs-triage
esm-infra/xenial_python-redis: needs-triage
trusty_python-redis: ignored (out of standard support)
xenial_python-redis: ignored (out of standard support)
bionic_python-redis: needs-triage
focal_python-redis: needs-triage
jammy_python-redis: needs-triage
kinetic_python-redis: needs-triage
devel_python-redis: needs-triage
