Candidate: CVE-2022-25304
PublicDate: 2022-08-23 05:15:00 UTC
References:
 https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25304
 https://github.com/FreeOpcUa/python-opcua/issues/1466
 https://security.snyk.io/vuln/SNYK-PYTHON-OPCUA-2988730
Description:
 All versions of package opcua; all versions of package asyncua are
 vulnerable to Denial of Service (DoS) due to a missing limitation on the
 number of received chunks - per single session or in total for all
 concurrent sessions. An attacker can exploit this vulnerability by sending
 an unlimited number of huge chunks (e.g. 2GB each) without sending the
 Final closing chunk.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]

Patches_python-opcua:
upstream_python-opcua: needs-triage
trusty_python-opcua: ignored (out of standard support)
xenial_python-opcua: ignored (out of standard support)
bionic_python-opcua: needs-triage
esm-apps/bionic_python-opcua: needs-triage
focal_python-opcua: needs-triage
esm-apps/focal_python-opcua: needs-triage
jammy_python-opcua: needs-triage
esm-apps/jammy_python-opcua: needs-triage
kinetic_python-opcua: DNE
devel_python-opcua: DNE
